helm:
  parameters:
  - name: backend.image.repository
    value: ghcr.io/mvulcu/maria-guestbook-backend
    forcestring: true
  - name: backend.image.tag
    value: latest
    forcestring: true
  - name: frontend.image.repository
    value: ghcr.io/mvulcu/maria-guestbook-frontend
    forcestring: true
  - name: frontend.image.tag
    value: latest
    forcestring: true
