apiVersion: v1
kind: Secret
metadata:
  name: maria-redis-secret
  labels:
    app.kubernetes.io/name: maria-redis
    app.kubernetes.io/part-of: maria-guestbook
type: Opaque
stringData:
  password: {{ .Values.redis.auth.password | quote }}
