apiVersion: v1
kind: ConfigMap
metadata:
  name: maria-app-config
  labels:
    {{- include "guestbook.labels" . | nindent 4 }}
data:
  REDIS_HOST: {{ .Values.backend.env.redisHost | quote }}
  REDIS_PORT: {{ .Values.backend.env.redisPort | quote }}
