apiVersion: v1
kind: ConfigMap
metadata:
  name: maria-frontend-nginx-config
  labels:
    {{- include "guestbook.frontend.labels" . | nindent 4 }}
data:
  nginx.conf: |
{{ .Files.Get "nginx.conf" | indent 4 }}
