{{- if .Values.networkPolicy.enabled -}}
# 1. Default Deny All Ingress
# -----------------------------------------------------------------------------
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
  labels:
    {{- include "guestbook.labels" . | nindent 4 }}
spec:
  podSelector: {} # Select all pods in namespace
  policyTypes:
    - Ingress
---
# 2. Allow Internet -> Frontend
# -----------------------------------------------------------------------------
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: frontend-allow-ingress
  labels:
    {{- include "guestbook.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "guestbook.frontend.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - from: [] # Allow from everywhere (Internet/Ingress)
      ports:
        - port: 8080
          protocol: TCP
---
# 3. Allow Frontend -> Backend
# -----------------------------------------------------------------------------
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: backend-allow-frontend
  labels:
    {{- include "guestbook.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "guestbook.backend.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              {{- include "guestbook.frontend.selectorLabels" . | nindent 14 }}
      ports:
        - port: 8080
          protocol: TCP
---
# 4. Allow Backend -> Redis
# -----------------------------------------------------------------------------
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: redis-allow-backend
  labels:
    {{- include "guestbook.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "guestbook.redis.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              {{- include "guestbook.backend.selectorLabels" . | nindent 14 }}
      ports:
        - port: 6379
          protocol: TCP
---
# 5. Allow Backend -> PostgreSQL
# -----------------------------------------------------------------------------
{{- if .Values.postgresql.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: postgres-allow-backend
  labels:
    {{- include "guestbook.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: maria-postgres
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              {{- include "guestbook.backend.selectorLabels" . | nindent 14 }}
      ports:
        - port: 5432
          protocol: TCP
{{- end }}
{{- end }}
